version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "--------->>>>>>>>>> FASE DE PRÉ BUILD <<<<<<<<<<---------"
      - mvn clean install
  build:
    commands:
      - echo "--------->>>>>>>>>> CRIANDO ARQUIVO .JAR <<<<<<<<<<---------"
      - mvn package
  post_build:
    commands:

artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes